
name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0


      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装依赖
        run: |
          npm install -g corepack
          corepack enable
          pnpm install --frozen-lockfile

      # - name: 动态修改 base 配置
      #   run: |
      #     sed -i 's|base: "/"|base: "/my-docs"|' src/.vuepress/config.ts
          
      # - name: 修改 assets 路径
      #   run: |
      #     sed -i 's|/assets|/my-docs/assets|g' src/.vuepress/theme.ts

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}       # 服务器IP或域名
          username: ${{ secrets.SSH_USERNAME }}  # SSH用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # SSH私钥（需配置到Secrets）
          script: |
            # 进入Nginx配置或源码目录
            cd /var/www/my-docs

            # 拉取最新代码（如果直接使用GitHub的代码，可跳过）
            git pull origin gh-pages

            # 平滑重载Nginx
            sudo nginx -s reload

            echo "Nginx reloaded successfully!"
